@startuml
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 100

entity "学生" as S <<entity>>
entity "课程" as C <<entity>>
circle "选修" as SC <<relationship>>

S -- SC : N
C -- SC : M
@enduml